### ISSUE TITLE
BUG-Syntax error with 'metric' element when running setup_generation.py

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-doc#1014]
**Bug description**
I followed INSTALLATION.md but get the following error when running `pipenv run python tools/setup_generation.py` at step 3/7 :

```
Traceback (most recent call last):
  File "/home/user/taipy-doc/tools/_setup_generation/step_viselements.py", line 389, in build_doc
    _ = eval(default_value)
  File "<string>", line 1, in <module>
NameError: name 'circular' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/taipy-doc/tools/setup_generation.py", line 26, in <module>
    run_setup(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), steps)
  File "/home/user/taipy-doc/tools/_setup_generation/setup.py", line 139, in run_setup
    setup.setup()
  File "/home/user/taipy-doc/tools/_setup_generation/setup.py", line 58, in setup
    step.setup(self)
  File "/home/user/taipy-doc/tools/_setup_generation/step_viselements.py", line 456, in setup
    self.generate_builder_api()
  File "/home/user/taipy-doc/tools/_setup_generation/step_viselements.py", line 450, in generate_builder_api
    file.write(generate(self, "controls", "_Control"))
  File "/home/user/taipy-doc/tools/_setup_generation/step_viselements.py", line 428, in generate
    doc = build_doc(property_name, property, doc_indent)
  File "/home/user/taipy-doc/tools/_setup_generation/step_viselements.py", line 391, in build_doc
    raise SyntaxError(f"Default value for property '{property}' of element '{element_type}' is not a valid Python expression ({default_value})")
SyntaxError: Default value for property 'type' of element 'metric' is not a valid Python expression (circular)
```

**Expected change**
Description of what would be the expected outcome.

**Screenshots**
When available and relevant, screenshots better help show the problem.

**Comment by arcanaxion** [comment]
Seems to work now
